library(limma)
library(edgeR)
library(biomaRt)
library(PLIER)
library(ggplot2)
library(RColorBrewer)
library(qvalue)
library(genefilter)
library(gridExtra)
library(dplyr)
library(data.table)
library(ternvis)
library(ggpubr)
library(cowplot)
library(plyr)
library(stringr)
library(UpSetR)
library(foreign)
library(MASS)
library(sfsmisc)
library(IHW)
library("org.Rn.eg.db")
library(MCL)
library(corrplot)
library(ggrepel)
library(CellCODE)
library(tidyverse)
library(ggsci)
library(circlize)
library(grid)
library(GenomicRanges)

setwd("C:/Users/gsmit/Documents/Mount Sinai/Sealfon Laboratory/MoTrPAC/PASS1B Raw Data")

load("rnasigl2fcmat.RData")
load("atacsigl2fcmat.RData")
load("methsigl2fcmat.RData")

load("omesigdata.RData")

rnasigagreement <- matrix(0L,nrow = 8,ncol = 9)
rownames(rnasigagreement) <- c("SKM-GN","HEART","HIPPOC","KIDNEY",
                               "LIVER","LUNG","BAT","WAT-SC")
colnames(rnasigagreement) <- c(-8,-6,-4,-2,0,2,4,6,8)

atacsigagreement <- matrix(0L,nrow = 8,ncol = 9)
rownames(atacsigagreement) <- c("SKM-GN","HEART","HIPPOC","KIDNEY",
                                "LIVER","LUNG","BAT","WAT-SC")
colnames(atacsigagreement) <- c(-8,-6,-4,-2,0,2,4,6,8)

methsigagreement <- matrix(0L,nrow = 8,ncol = 9)
rownames(methsigagreement) <- c("SKM-GN","HEART","HIPPOC","KIDNEY",
                                "LIVER","LUNG","BAT","WAT-SC")
colnames(methsigagreement) <- c(-8,-6,-4,-2,0,2,4,6,8)



# SKM-GN / gastro

rnasigagreement["SKM-GN","-8"] <- sum(rowSums(sign(gastrosigrnal2fc)) == -8)/length(gastrornasig)
rnasigagreement["SKM-GN","-6"] <- sum(rowSums(sign(gastrosigrnal2fc)) == -6)/length(gastrornasig)
rnasigagreement["SKM-GN","-4"] <- sum(rowSums(sign(gastrosigrnal2fc)) == -4)/length(gastrornasig)
rnasigagreement["SKM-GN","-2"] <- sum(rowSums(sign(gastrosigrnal2fc)) == -2)/length(gastrornasig)
rnasigagreement["SKM-GN","0"] <- sum(rowSums(sign(gastrosigrnal2fc)) == 0)/length(gastrornasig)
rnasigagreement["SKM-GN","2"] <- sum(rowSums(sign(gastrosigrnal2fc)) == 2)/length(gastrornasig)
rnasigagreement["SKM-GN","4"] <- sum(rowSums(sign(gastrosigrnal2fc)) == 4)/length(gastrornasig)
rnasigagreement["SKM-GN","6"] <- sum(rowSums(sign(gastrosigrnal2fc)) == 6)/length(gastrornasig)
rnasigagreement["SKM-GN","8"] <- sum(rowSums(sign(gastrosigrnal2fc)) == 8)/length(gastrornasig)

atacsigagreement["SKM-GN","-8"] <- sum(rowSums(sign(gastrosigatacl2fc)) == -8)/length(gastroatacsig)
atacsigagreement["SKM-GN","-6"] <- sum(rowSums(sign(gastrosigatacl2fc)) == -6)/length(gastroatacsig)
atacsigagreement["SKM-GN","-4"] <- sum(rowSums(sign(gastrosigatacl2fc)) == -4)/length(gastroatacsig)
atacsigagreement["SKM-GN","-2"] <- sum(rowSums(sign(gastrosigatacl2fc)) == -2)/length(gastroatacsig)
atacsigagreement["SKM-GN","0"] <- sum(rowSums(sign(gastrosigatacl2fc)) == 0)/length(gastroatacsig)
atacsigagreement["SKM-GN","2"] <- sum(rowSums(sign(gastrosigatacl2fc)) == 2)/length(gastroatacsig)
atacsigagreement["SKM-GN","4"] <- sum(rowSums(sign(gastrosigatacl2fc)) == 4)/length(gastroatacsig)
atacsigagreement["SKM-GN","6"] <- sum(rowSums(sign(gastrosigatacl2fc)) == 6)/length(gastroatacsig)
atacsigagreement["SKM-GN","8"] <- sum(rowSums(sign(gastrosigatacl2fc)) == 8)/length(gastroatacsig)

methsigagreement["SKM-GN","-8"] <- sum(rowSums(sign(gastromethl2fc)) == -8)/length(gastromethsig)
methsigagreement["SKM-GN","-6"] <- sum(rowSums(sign(gastromethl2fc)) == -6)/length(gastromethsig)
methsigagreement["SKM-GN","-4"] <- sum(rowSums(sign(gastromethl2fc)) == -4)/length(gastromethsig)
methsigagreement["SKM-GN","-2"] <- sum(rowSums(sign(gastromethl2fc)) == -2)/length(gastromethsig)
methsigagreement["SKM-GN","0"] <- sum(rowSums(sign(gastromethl2fc)) == 0)/length(gastromethsig)
methsigagreement["SKM-GN","2"] <- sum(rowSums(sign(gastromethl2fc)) == 2)/length(gastromethsig)
methsigagreement["SKM-GN","4"] <- sum(rowSums(sign(gastromethl2fc)) == 4)/length(gastromethsig)
methsigagreement["SKM-GN","6"] <- sum(rowSums(sign(gastromethl2fc)) == 6)/length(gastromethsig)
methsigagreement["SKM-GN","8"] <- sum(rowSums(sign(gastromethl2fc)) == 8)/length(gastromethsig)

# HEART / heart

rnasigagreement["HEART","-8"] <- sum(rowSums(sign(heartsigrnal2fc)) == -8)/length(heartrnasig)
rnasigagreement["HEART","-6"] <- sum(rowSums(sign(heartsigrnal2fc)) == -6)/length(heartrnasig)
rnasigagreement["HEART","-4"] <- sum(rowSums(sign(heartsigrnal2fc)) == -4)/length(heartrnasig)
rnasigagreement["HEART","-2"] <- sum(rowSums(sign(heartsigrnal2fc)) == -2)/length(heartrnasig)
rnasigagreement["HEART","0"] <- sum(rowSums(sign(heartsigrnal2fc)) == 0)/length(heartrnasig)
rnasigagreement["HEART","2"] <- sum(rowSums(sign(heartsigrnal2fc)) == 2)/length(heartrnasig)
rnasigagreement["HEART","4"] <- sum(rowSums(sign(heartsigrnal2fc)) == 4)/length(heartrnasig)
rnasigagreement["HEART","6"] <- sum(rowSums(sign(heartsigrnal2fc)) == 6)/length(heartrnasig)
rnasigagreement["HEART","8"] <- sum(rowSums(sign(heartsigrnal2fc)) == 8)/length(heartrnasig)

atacsigagreement["HEART","-8"] <- sum(rowSums(sign(heartsigatacl2fc)) == -8)/length(heartatacsig)
atacsigagreement["HEART","-6"] <- sum(rowSums(sign(heartsigatacl2fc)) == -6)/length(heartatacsig)
atacsigagreement["HEART","-4"] <- sum(rowSums(sign(heartsigatacl2fc)) == -4)/length(heartatacsig)
atacsigagreement["HEART","-2"] <- sum(rowSums(sign(heartsigatacl2fc)) == -2)/length(heartatacsig)
atacsigagreement["HEART","0"] <- sum(rowSums(sign(heartsigatacl2fc)) == 0)/length(heartatacsig)
atacsigagreement["HEART","2"] <- sum(rowSums(sign(heartsigatacl2fc)) == 2)/length(heartatacsig)
atacsigagreement["HEART","4"] <- sum(rowSums(sign(heartsigatacl2fc)) == 4)/length(heartatacsig)
atacsigagreement["HEART","6"] <- sum(rowSums(sign(heartsigatacl2fc)) == 6)/length(heartatacsig)
atacsigagreement["HEART","8"] <- sum(rowSums(sign(heartsigatacl2fc)) == 8)/length(heartatacsig)

methsigagreement["HEART","-8"] <- sum(rowSums(sign(heartmethl2fc)) == -8)/length(heartmethsig)
methsigagreement["HEART","-6"] <- sum(rowSums(sign(heartmethl2fc)) == -6)/length(heartmethsig)
methsigagreement["HEART","-4"] <- sum(rowSums(sign(heartmethl2fc)) == -4)/length(heartmethsig)
methsigagreement["HEART","-2"] <- sum(rowSums(sign(heartmethl2fc)) == -2)/length(heartmethsig)
methsigagreement["HEART","0"] <- sum(rowSums(sign(heartmethl2fc)) == 0)/length(heartmethsig)
methsigagreement["HEART","2"] <- sum(rowSums(sign(heartmethl2fc)) == 2)/length(heartmethsig)
methsigagreement["HEART","4"] <- sum(rowSums(sign(heartmethl2fc)) == 4)/length(heartmethsig)
methsigagreement["HEART","6"] <- sum(rowSums(sign(heartmethl2fc)) == 6)/length(heartmethsig)
methsigagreement["HEART","8"] <- sum(rowSums(sign(heartmethl2fc)) == 8)/length(heartmethsig)

# HIPPOC / hippo

rnasigagreement["HIPPOC","-8"] <- sum(rowSums(sign(hipposigrnal2fc)) == -8)/length(hippornasig)
rnasigagreement["HIPPOC","-6"] <- sum(rowSums(sign(hipposigrnal2fc)) == -6)/length(hippornasig)
rnasigagreement["HIPPOC","-4"] <- sum(rowSums(sign(hipposigrnal2fc)) == -4)/length(hippornasig)
rnasigagreement["HIPPOC","-2"] <- sum(rowSums(sign(hipposigrnal2fc)) == -2)/length(hippornasig)
rnasigagreement["HIPPOC","0"] <- sum(rowSums(sign(hipposigrnal2fc)) == 0)/length(hippornasig)
rnasigagreement["HIPPOC","2"] <- sum(rowSums(sign(hipposigrnal2fc)) == 2)/length(hippornasig)
rnasigagreement["HIPPOC","4"] <- sum(rowSums(sign(hipposigrnal2fc)) == 4)/length(hippornasig)
rnasigagreement["HIPPOC","6"] <- sum(rowSums(sign(hipposigrnal2fc)) == 6)/length(hippornasig)
rnasigagreement["HIPPOC","8"] <- sum(rowSums(sign(hipposigrnal2fc)) == 8)/length(hippornasig)

atacsigagreement["HIPPOC","-8"] <- sum(rowSums(sign(hipposigatacl2fc)) == -8)/length(hippoatacsig)
atacsigagreement["HIPPOC","-6"] <- sum(rowSums(sign(hipposigatacl2fc)) == -6)/length(hippoatacsig)
atacsigagreement["HIPPOC","-4"] <- sum(rowSums(sign(hipposigatacl2fc)) == -4)/length(hippoatacsig)
atacsigagreement["HIPPOC","-2"] <- sum(rowSums(sign(hipposigatacl2fc)) == -2)/length(hippoatacsig)
atacsigagreement["HIPPOC","0"] <- sum(rowSums(sign(hipposigatacl2fc)) == 0)/length(hippoatacsig)
atacsigagreement["HIPPOC","2"] <- sum(rowSums(sign(hipposigatacl2fc)) == 2)/length(hippoatacsig)
atacsigagreement["HIPPOC","4"] <- sum(rowSums(sign(hipposigatacl2fc)) == 4)/length(hippoatacsig)
atacsigagreement["HIPPOC","6"] <- sum(rowSums(sign(hipposigatacl2fc)) == 6)/length(hippoatacsig)
atacsigagreement["HIPPOC","8"] <- sum(rowSums(sign(hipposigatacl2fc)) == 8)/length(hippoatacsig)

methsigagreement["HIPPOC","-8"] <- sum(rowSums(sign(hippomethl2fc)) == -8)/length(hippomethsig)
methsigagreement["HIPPOC","-6"] <- sum(rowSums(sign(hippomethl2fc)) == -6)/length(hippomethsig)
methsigagreement["HIPPOC","-4"] <- sum(rowSums(sign(hippomethl2fc)) == -4)/length(hippomethsig)
methsigagreement["HIPPOC","-2"] <- sum(rowSums(sign(hippomethl2fc)) == -2)/length(hippomethsig)
methsigagreement["HIPPOC","0"] <- sum(rowSums(sign(hippomethl2fc)) == 0)/length(hippomethsig)
methsigagreement["HIPPOC","2"] <- sum(rowSums(sign(hippomethl2fc)) == 2)/length(hippomethsig)
methsigagreement["HIPPOC","4"] <- sum(rowSums(sign(hippomethl2fc)) == 4)/length(hippomethsig)
methsigagreement["HIPPOC","6"] <- sum(rowSums(sign(hippomethl2fc)) == 6)/length(hippomethsig)
methsigagreement["HIPPOC","8"] <- sum(rowSums(sign(hippomethl2fc)) == 8)/length(hippomethsig)

# KIDNEY / kidney

rnasigagreement["KIDNEY","-8"] <- sum(rowSums(sign(kidneysigrnal2fc)) == -8)/length(kidneyrnasig)
rnasigagreement["KIDNEY","-6"] <- sum(rowSums(sign(kidneysigrnal2fc)) == -6)/length(kidneyrnasig)
rnasigagreement["KIDNEY","-4"] <- sum(rowSums(sign(kidneysigrnal2fc)) == -4)/length(kidneyrnasig)
rnasigagreement["KIDNEY","-2"] <- sum(rowSums(sign(kidneysigrnal2fc)) == -2)/length(kidneyrnasig)
rnasigagreement["KIDNEY","0"] <- sum(rowSums(sign(kidneysigrnal2fc)) == 0)/length(kidneyrnasig)
rnasigagreement["KIDNEY","2"] <- sum(rowSums(sign(kidneysigrnal2fc)) == 2)/length(kidneyrnasig)
rnasigagreement["KIDNEY","4"] <- sum(rowSums(sign(kidneysigrnal2fc)) == 4)/length(kidneyrnasig)
rnasigagreement["KIDNEY","6"] <- sum(rowSums(sign(kidneysigrnal2fc)) == 6)/length(kidneyrnasig)
rnasigagreement["KIDNEY","8"] <- sum(rowSums(sign(kidneysigrnal2fc)) == 8)/length(kidneyrnasig)

atacsigagreement["KIDNEY","-8"] <- sum(rowSums(sign(kidneysigatacl2fc)) == -8)/length(kidneyatacsig)
atacsigagreement["KIDNEY","-6"] <- sum(rowSums(sign(kidneysigatacl2fc)) == -6)/length(kidneyatacsig)
atacsigagreement["KIDNEY","-4"] <- sum(rowSums(sign(kidneysigatacl2fc)) == -4)/length(kidneyatacsig)
atacsigagreement["KIDNEY","-2"] <- sum(rowSums(sign(kidneysigatacl2fc)) == -2)/length(kidneyatacsig)
atacsigagreement["KIDNEY","0"] <- sum(rowSums(sign(kidneysigatacl2fc)) == 0)/length(kidneyatacsig)
atacsigagreement["KIDNEY","2"] <- sum(rowSums(sign(kidneysigatacl2fc)) == 2)/length(kidneyatacsig)
atacsigagreement["KIDNEY","4"] <- sum(rowSums(sign(kidneysigatacl2fc)) == 4)/length(kidneyatacsig)
atacsigagreement["KIDNEY","6"] <- sum(rowSums(sign(kidneysigatacl2fc)) == 6)/length(kidneyatacsig)
atacsigagreement["KIDNEY","8"] <- sum(rowSums(sign(kidneysigatacl2fc)) == 8)/length(kidneyatacsig)

methsigagreement["KIDNEY","-8"] <- sum(rowSums(sign(kidneymethl2fc)) == -8)/length(kidneymethsig)
methsigagreement["KIDNEY","-6"] <- sum(rowSums(sign(kidneymethl2fc)) == -6)/length(kidneymethsig)
methsigagreement["KIDNEY","-4"] <- sum(rowSums(sign(kidneymethl2fc)) == -4)/length(kidneymethsig)
methsigagreement["KIDNEY","-2"] <- sum(rowSums(sign(kidneymethl2fc)) == -2)/length(kidneymethsig)
methsigagreement["KIDNEY","0"] <- sum(rowSums(sign(kidneymethl2fc)) == 0)/length(kidneymethsig)
methsigagreement["KIDNEY","2"] <- sum(rowSums(sign(kidneymethl2fc)) == 2)/length(kidneymethsig)
methsigagreement["KIDNEY","4"] <- sum(rowSums(sign(kidneymethl2fc)) == 4)/length(kidneymethsig)
methsigagreement["KIDNEY","6"] <- sum(rowSums(sign(kidneymethl2fc)) == 6)/length(kidneymethsig)
methsigagreement["KIDNEY","8"] <- sum(rowSums(sign(kidneymethl2fc)) == 8)/length(kidneymethsig)

# LIVER / liver

rnasigagreement["LIVER","-8"] <- sum(rowSums(sign(liversigrnal2fc)) == -8)/length(liverrnasig)
rnasigagreement["LIVER","-6"] <- sum(rowSums(sign(liversigrnal2fc)) == -6)/length(liverrnasig)
rnasigagreement["LIVER","-4"] <- sum(rowSums(sign(liversigrnal2fc)) == -4)/length(liverrnasig)
rnasigagreement["LIVER","-2"] <- sum(rowSums(sign(liversigrnal2fc)) == -2)/length(liverrnasig)
rnasigagreement["LIVER","0"] <- sum(rowSums(sign(liversigrnal2fc)) == 0)/length(liverrnasig)
rnasigagreement["LIVER","2"] <- sum(rowSums(sign(liversigrnal2fc)) == 2)/length(liverrnasig)
rnasigagreement["LIVER","4"] <- sum(rowSums(sign(liversigrnal2fc)) == 4)/length(liverrnasig)
rnasigagreement["LIVER","6"] <- sum(rowSums(sign(liversigrnal2fc)) == 6)/length(liverrnasig)
rnasigagreement["LIVER","8"] <- sum(rowSums(sign(liversigrnal2fc)) == 8)/length(liverrnasig)

atacsigagreement["LIVER","-8"] <- sum(rowSums(sign(liversigatacl2fc)) == -8)/length(liveratacsig)
atacsigagreement["LIVER","-6"] <- sum(rowSums(sign(liversigatacl2fc)) == -6)/length(liveratacsig)
atacsigagreement["LIVER","-4"] <- sum(rowSums(sign(liversigatacl2fc)) == -4)/length(liveratacsig)
atacsigagreement["LIVER","-2"] <- sum(rowSums(sign(liversigatacl2fc)) == -2)/length(liveratacsig)
atacsigagreement["LIVER","0"] <- sum(rowSums(sign(liversigatacl2fc)) == 0)/length(liveratacsig)
atacsigagreement["LIVER","2"] <- sum(rowSums(sign(liversigatacl2fc)) == 2)/length(liveratacsig)
atacsigagreement["LIVER","4"] <- sum(rowSums(sign(liversigatacl2fc)) == 4)/length(liveratacsig)
atacsigagreement["LIVER","6"] <- sum(rowSums(sign(liversigatacl2fc)) == 6)/length(liveratacsig)
atacsigagreement["LIVER","8"] <- sum(rowSums(sign(liversigatacl2fc)) == 8)/length(liveratacsig)

methsigagreement["LIVER","-8"] <- sum(rowSums(sign(livermethl2fc)) == -8)/length(livermethsig)
methsigagreement["LIVER","-6"] <- sum(rowSums(sign(livermethl2fc)) == -6)/length(livermethsig)
methsigagreement["LIVER","-4"] <- sum(rowSums(sign(livermethl2fc)) == -4)/length(livermethsig)
methsigagreement["LIVER","-2"] <- sum(rowSums(sign(livermethl2fc)) == -2)/length(livermethsig)
methsigagreement["LIVER","0"] <- sum(rowSums(sign(livermethl2fc)) == 0)/length(livermethsig)
methsigagreement["LIVER","2"] <- sum(rowSums(sign(livermethl2fc)) == 2)/length(livermethsig)
methsigagreement["LIVER","4"] <- sum(rowSums(sign(livermethl2fc)) == 4)/length(livermethsig)
methsigagreement["LIVER","6"] <- sum(rowSums(sign(livermethl2fc)) == 6)/length(livermethsig)
methsigagreement["LIVER","8"] <- sum(rowSums(sign(livermethl2fc)) == 8)/length(livermethsig)

# LUNG / lung

rnasigagreement["LUNG","-8"] <- sum(rowSums(sign(lungsigrnal2fc)) == -8)/length(lungrnasig)
rnasigagreement["LUNG","-6"] <- sum(rowSums(sign(lungsigrnal2fc)) == -6)/length(lungrnasig)
rnasigagreement["LUNG","-4"] <- sum(rowSums(sign(lungsigrnal2fc)) == -4)/length(lungrnasig)
rnasigagreement["LUNG","-2"] <- sum(rowSums(sign(lungsigrnal2fc)) == -2)/length(lungrnasig)
rnasigagreement["LUNG","0"] <- sum(rowSums(sign(lungsigrnal2fc)) == 0)/length(lungrnasig)
rnasigagreement["LUNG","2"] <- sum(rowSums(sign(lungsigrnal2fc)) == 2)/length(lungrnasig)
rnasigagreement["LUNG","4"] <- sum(rowSums(sign(lungsigrnal2fc)) == 4)/length(lungrnasig)
rnasigagreement["LUNG","6"] <- sum(rowSums(sign(lungsigrnal2fc)) == 6)/length(lungrnasig)
rnasigagreement["LUNG","8"] <- sum(rowSums(sign(lungsigrnal2fc)) == 8)/length(lungrnasig)

atacsigagreement["LUNG","-8"] <- sum(rowSums(sign(lungsigatacl2fc)) == -8)/length(lungatacsig)
atacsigagreement["LUNG","-6"] <- sum(rowSums(sign(lungsigatacl2fc)) == -6)/length(lungatacsig)
atacsigagreement["LUNG","-4"] <- sum(rowSums(sign(lungsigatacl2fc)) == -4)/length(lungatacsig)
atacsigagreement["LUNG","-2"] <- sum(rowSums(sign(lungsigatacl2fc)) == -2)/length(lungatacsig)
atacsigagreement["LUNG","0"] <- sum(rowSums(sign(lungsigatacl2fc)) == 0)/length(lungatacsig)
atacsigagreement["LUNG","2"] <- sum(rowSums(sign(lungsigatacl2fc)) == 2)/length(lungatacsig)
atacsigagreement["LUNG","4"] <- sum(rowSums(sign(lungsigatacl2fc)) == 4)/length(lungatacsig)
atacsigagreement["LUNG","6"] <- sum(rowSums(sign(lungsigatacl2fc)) == 6)/length(lungatacsig)
atacsigagreement["LUNG","8"] <- sum(rowSums(sign(lungsigatacl2fc)) == 8)/length(lungatacsig)

methsigagreement["LUNG","-8"] <- sum(rowSums(sign(lungmethl2fc)) == -8)/length(lungmethsig)
methsigagreement["LUNG","-6"] <- sum(rowSums(sign(lungmethl2fc)) == -6)/length(lungmethsig)
methsigagreement["LUNG","-4"] <- sum(rowSums(sign(lungmethl2fc)) == -4)/length(lungmethsig)
methsigagreement["LUNG","-2"] <- sum(rowSums(sign(lungmethl2fc)) == -2)/length(lungmethsig)
methsigagreement["LUNG","0"] <- sum(rowSums(sign(lungmethl2fc)) == 0)/length(lungmethsig)
methsigagreement["LUNG","2"] <- sum(rowSums(sign(lungmethl2fc)) == 2)/length(lungmethsig)
methsigagreement["LUNG","4"] <- sum(rowSums(sign(lungmethl2fc)) == 4)/length(lungmethsig)
methsigagreement["LUNG","6"] <- sum(rowSums(sign(lungmethl2fc)) == 6)/length(lungmethsig)
methsigagreement["LUNG","8"] <- sum(rowSums(sign(lungmethl2fc)) == 8)/length(lungmethsig)

# BAT / brown

rnasigagreement["BAT","-8"] <- sum(rowSums(sign(brownsigrnal2fc)) == -8)/length(brownrnasig)
rnasigagreement["BAT","-6"] <- sum(rowSums(sign(brownsigrnal2fc)) == -6)/length(brownrnasig)
rnasigagreement["BAT","-4"] <- sum(rowSums(sign(brownsigrnal2fc)) == -4)/length(brownrnasig)
rnasigagreement["BAT","-2"] <- sum(rowSums(sign(brownsigrnal2fc)) == -2)/length(brownrnasig)
rnasigagreement["BAT","0"] <- sum(rowSums(sign(brownsigrnal2fc)) == 0)/length(brownrnasig)
rnasigagreement["BAT","2"] <- sum(rowSums(sign(brownsigrnal2fc)) == 2)/length(brownrnasig)
rnasigagreement["BAT","4"] <- sum(rowSums(sign(brownsigrnal2fc)) == 4)/length(brownrnasig)
rnasigagreement["BAT","6"] <- sum(rowSums(sign(brownsigrnal2fc)) == 6)/length(brownrnasig)
rnasigagreement["BAT","8"] <- sum(rowSums(sign(brownsigrnal2fc)) == 8)/length(brownrnasig)

atacsigagreement["BAT","-8"] <- sum(rowSums(sign(brownsigatacl2fc)) == -8)/length(brownatacsig)
atacsigagreement["BAT","-6"] <- sum(rowSums(sign(brownsigatacl2fc)) == -6)/length(brownatacsig)
atacsigagreement["BAT","-4"] <- sum(rowSums(sign(brownsigatacl2fc)) == -4)/length(brownatacsig)
atacsigagreement["BAT","-2"] <- sum(rowSums(sign(brownsigatacl2fc)) == -2)/length(brownatacsig)
atacsigagreement["BAT","0"] <- sum(rowSums(sign(brownsigatacl2fc)) == 0)/length(brownatacsig)
atacsigagreement["BAT","2"] <- sum(rowSums(sign(brownsigatacl2fc)) == 2)/length(brownatacsig)
atacsigagreement["BAT","4"] <- sum(rowSums(sign(brownsigatacl2fc)) == 4)/length(brownatacsig)
atacsigagreement["BAT","6"] <- sum(rowSums(sign(brownsigatacl2fc)) == 6)/length(brownatacsig)
atacsigagreement["BAT","8"] <- sum(rowSums(sign(brownsigatacl2fc)) == 8)/length(brownatacsig)

methsigagreement["BAT","-8"] <- sum(rowSums(sign(brownmethl2fc)) == -8)/length(brownmethsig)
methsigagreement["BAT","-6"] <- sum(rowSums(sign(brownmethl2fc)) == -6)/length(brownmethsig)
methsigagreement["BAT","-4"] <- sum(rowSums(sign(brownmethl2fc)) == -4)/length(brownmethsig)
methsigagreement["BAT","-2"] <- sum(rowSums(sign(brownmethl2fc)) == -2)/length(brownmethsig)
methsigagreement["BAT","0"] <- sum(rowSums(sign(brownmethl2fc)) == 0)/length(brownmethsig)
methsigagreement["BAT","2"] <- sum(rowSums(sign(brownmethl2fc)) == 2)/length(brownmethsig)
methsigagreement["BAT","4"] <- sum(rowSums(sign(brownmethl2fc)) == 4)/length(brownmethsig)
methsigagreement["BAT","6"] <- sum(rowSums(sign(brownmethl2fc)) == 6)/length(brownmethsig)
methsigagreement["BAT","8"] <- sum(rowSums(sign(brownmethl2fc)) == 8)/length(brownmethsig)

# WAT-SC / white

rnasigagreement["WAT-SC","-8"] <- sum(rowSums(sign(whitesigrnal2fc)) == -8)/length(whiternasig)
rnasigagreement["WAT-SC","-6"] <- sum(rowSums(sign(whitesigrnal2fc)) == -6)/length(whiternasig)
rnasigagreement["WAT-SC","-4"] <- sum(rowSums(sign(whitesigrnal2fc)) == -4)/length(whiternasig)
rnasigagreement["WAT-SC","-2"] <- sum(rowSums(sign(whitesigrnal2fc)) == -2)/length(whiternasig)
rnasigagreement["WAT-SC","0"] <- sum(rowSums(sign(whitesigrnal2fc)) == 0)/length(whiternasig)
rnasigagreement["WAT-SC","2"] <- sum(rowSums(sign(whitesigrnal2fc)) == 2)/length(whiternasig)
rnasigagreement["WAT-SC","4"] <- sum(rowSums(sign(whitesigrnal2fc)) == 4)/length(whiternasig)
rnasigagreement["WAT-SC","6"] <- sum(rowSums(sign(whitesigrnal2fc)) == 6)/length(whiternasig)
rnasigagreement["WAT-SC","8"] <- sum(rowSums(sign(whitesigrnal2fc)) == 8)/length(whiternasig)

atacsigagreement["WAT-SC","-8"] <- sum(rowSums(sign(whitesigatacl2fc)) == -8)/length(whiteatacsig)
atacsigagreement["WAT-SC","-6"] <- sum(rowSums(sign(whitesigatacl2fc)) == -6)/length(whiteatacsig)
atacsigagreement["WAT-SC","-4"] <- sum(rowSums(sign(whitesigatacl2fc)) == -4)/length(whiteatacsig)
atacsigagreement["WAT-SC","-2"] <- sum(rowSums(sign(whitesigatacl2fc)) == -2)/length(whiteatacsig)
atacsigagreement["WAT-SC","0"] <- sum(rowSums(sign(whitesigatacl2fc)) == 0)/length(whiteatacsig)
atacsigagreement["WAT-SC","2"] <- sum(rowSums(sign(whitesigatacl2fc)) == 2)/length(whiteatacsig)
atacsigagreement["WAT-SC","4"] <- sum(rowSums(sign(whitesigatacl2fc)) == 4)/length(whiteatacsig)
atacsigagreement["WAT-SC","6"] <- sum(rowSums(sign(whitesigatacl2fc)) == 6)/length(whiteatacsig)
atacsigagreement["WAT-SC","8"] <- sum(rowSums(sign(whitesigatacl2fc)) == 8)/length(whiteatacsig)

methsigagreement["WAT-SC","-8"] <- sum(rowSums(sign(whitemethl2fc)) == -8)/length(whitemethsig)
methsigagreement["WAT-SC","-6"] <- sum(rowSums(sign(whitemethl2fc)) == -6)/length(whitemethsig)
methsigagreement["WAT-SC","-4"] <- sum(rowSums(sign(whitemethl2fc)) == -4)/length(whitemethsig)
methsigagreement["WAT-SC","-2"] <- sum(rowSums(sign(whitemethl2fc)) == -2)/length(whitemethsig)
methsigagreement["WAT-SC","0"] <- sum(rowSums(sign(whitemethl2fc)) == 0)/length(whitemethsig)
methsigagreement["WAT-SC","2"] <- sum(rowSums(sign(whitemethl2fc)) == 2)/length(whitemethsig)
methsigagreement["WAT-SC","4"] <- sum(rowSums(sign(whitemethl2fc)) == 4)/length(whitemethsig)
methsigagreement["WAT-SC","6"] <- sum(rowSums(sign(whitemethl2fc)) == 6)/length(whitemethsig)
methsigagreement["WAT-SC","8"] <- sum(rowSums(sign(whitemethl2fc)) == 8)/length(whitemethsig)

png(filename = "Figure 1Di_112624.png",height = 2.5,width = 6,units = "in",res = 600)
pheatmap(rnasigagreement,cluster_rows = T,cluster_cols = F,breaks = seq(0,0.25,length.out = 101),color = colorpanel(101,"white","firebrick"),angle_col = 0,fontsize = 14,border_color = NA)
dev.off()

png(filename = "Figure 1Dii_112624.png",height = 2.5,width = 6,units = "in",res = 600)
pheatmap(atacsigagreement,cluster_rows = T,cluster_cols = F,breaks = seq(0,0.25,length.out = 101),color = colorpanel(101,"white","steelblue4"),angle_col = 0,fontsize = 14,border_color = NA)
dev.off()

png(filename = "Figure 1Diii_112624.png",height = 2.5,width = 6,units = "in",res = 600)
pheatmap(methsigagreement,cluster_rows = T,cluster_cols = F,breaks = seq(0,0.25,length.out = 101),color = colorpanel(101,"white","darkgreen"),angle_col = 0,fontsize = 14,border_color = NA)
dev.off()


pdf(file = "Figure 1Di_112624.pdf",height = 2.5,width = 6)
pheatmap(rnasigagreement,cluster_rows = T,cluster_cols = F,breaks = seq(0,0.25,length.out = 101),color = colorpanel(101,"white","firebrick"),angle_col = 0,fontsize = 14,border_color = NA)
dev.off()

pdf(file = "Figure 1Dii_112624.pdf",height = 2.5,width = 6)
pheatmap(atacsigagreement,cluster_rows = T,cluster_cols = F,breaks = seq(0,0.25,length.out = 101),color = colorpanel(101,"white","steelblue4"),angle_col = 0,fontsize = 14,border_color = NA)
dev.off()

pdf(file = "Figure 1Diii_112624.pdf",height = 2.5,width = 6)
pheatmap(methsigagreement,cluster_rows = T,cluster_cols = F,breaks = seq(0,0.25,length.out = 101),color = colorpanel(101,"white","darkgreen"),angle_col = 0,fontsize = 14,border_color = NA)
dev.off()

save.image("Figure1D.RData")